### ISSUE TITLE
weave failing during test_all.py

### ISSUE THREAD

**Issue by dynaryu** [GeoscienceAustralia/eqrm#145]
I've got the following error message when I run test_all.py
# 
## ERROR: test_Sadigh_97_distribution (test_ground_motion_interface.Test_ground_motion_interface)

Traceback (most recent call last):
  File "/nas/gemd/e3p/sandpits/hryu/eqrm/eqrm_code/../eqrm_code/test_ground_motion_interface.py", line 154, in test_Sadigh_97_distribution
    sigma_coefficient=sigma_coefficient)
  File "/nas/gemd/e3p/sandpits/hryu/eqrm/eqrm_code/ground_motion_interface.py", line 1117, in Sadigh_97_distribution
    compiler='gcc')
  File "/usr/lib64/python2.7/site-packages/scipy/weave/inline_tools.py", line 359, in inline
    function_catalog.add_function(code,func,module_dir)
  File "/usr/lib64/python2.7/site-packages/scipy/weave/catalog.py", line 819, in add_function
    self.add_function_persistent(code,function)
  File "/usr/lib64/python2.7/site-packages/scipy/weave/catalog.py", line 854, in add_function_persistent
    function_list = function_list + cat.get(code,[])
  File "/usr/lib64/python2.7/shelve.py", line 114, in get
    return self[key]
  File "/usr/lib64/python2.7/shelve.py", line 122, in **getitem**
    value = Unpickler(f).load()
UnpicklingError: invalid load key, 'x'.

**Comment by dunkgray** [comment]
Hi Hyeuk,
Based on https://github.com/ioam/topographica/issues/237
Is there a ~/.pythonxx_compiled directory that you can delete and try again?

Cheers
Duncan
